[paths]
exist = [
    "$GOPATH/src/github.com/onsi/gomega"
]

[environment]
variables = [
    "$GOBIN",
    "$GOPATH",
]

[tools]
    [tools.nim]
    command = "nim -v"
    version-regex = 'Nim Compiler Version (\d+\.\d+\.\d+)'
    version-required = "^0.19.2"
    url = "https://nim-lang.org/"
